
title: XIAOPAN LYU
email: xiaopanlyu@outlook.com
description: Let it go!

url: https://xiaopanlyu.github.io
baseurl: ""
twitter_username: xiaopanlyu
github_username:  xiaopanlyu
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown

# highlight
# 本地用rouge, github上用pygments
highlighter: pygments
 #highlighter: rouge
 #highlighter: false
